org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.12.2
minecraft_version_range=[1.12.2]
forge_version=14.23.5.2859
forge_version_range=[14.23.5.2859,)
loader_version_range=[14,)
mapping_channel=stable
mapping_version=39-1.12

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=240982

mod_id=poweradvantage
mod_name=Power Advantage
mod_license=LGPL-3.0-only
mod_version=2.4.1.112021
mod_group=com.mcmoddev.poweradvantage
mod_authors=DrCyano (aka Cyanobacterium)
mod_description=API and shared machines for pressure, electricity, quantum power, fluids, and item transport.

cf_requirements=base-metals,mmd-orespawn
cf_optionals=additional-loot-tables
cf_versions=1.12.2

reborncore_version=3.19.4.529
reborncore_curse_project_id=500866
reborncore_curse_file_id=3386724
reborncore_download_url=https://maven.modmuss50.me/RebornCore/RebornCore-1.12.2/3.19.4.529/RebornCore-1.12.2-3.19.4.529-universal.jar
reborncore_sha256=B6D11200C5EC66B0031EF4E635AC0203A23CBA6B21F046D402D41E3375798667
rf_api_sha256=000BC4DACE68B13BF210177A68F3854C724623EA8F05AC9CDBD9DEBC63ABF62D
